### ISSUE TITLE
Feature enhancements

### ISSUE THREAD

**Issue by stenh0use** [victorock/ansible-role-tower-config#11]
We've been using your role to manage our tower config and code deployments to tower.

We've added a few enhancements, some specific to our architecture. Some are pre-release to ansible 2.8 which uses the new tower notification module.

- Notifications
- SAML config
- Organisation instance group assignment 
- Virtual Env assignment
- +Bug fixes

Would you be open to us creating pull request?

**Comment by victorock** [comment]
Awesome @spookiej !!!
Absolutely, PRs are always welcomed.

**Comment by stenh0use** [comment]
Cool, will send some through shortly
